Portfolio: validate contact form
a-laarabi/Portfolio_template-1 pull request #2
Opened 2022-06-23 15:20 UTC by a-laarabi

#What?
> Create a validation for the contact form, to make sure that the user mail should be lowercase.

2022-06-23 15:28 UTC, tufoinnkuo10 requested changes
Hi @a-laarabi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that has commits just from one partner. this is a group project and your partner has to participate in your project so he should have commit(s) as well

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-23 15:36 UTC, a-laarabi commented
hello @tufoinnkuo10 
I want to mention that I already worked with my partner on my second repo but I had a problem with linters (they give me errors with line that don't even exist and when I check them on my laptop everything seems good but in GitHub they give errors)on it so because of that I created this new one.
I would like you to consider that, please.
the link to my old repositories https://github.com/a-laarabi/Portfolio_Mobile-version/pull/16

2022-06-24 10:34 UTC, Mre55 requested changes
**Hi @a-laarabi,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 

- [ ] To keep the commit even the person with less commit should have to do this change.

_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 10:34 UTC, Mre55 commented on index.html
> +                 <li><span class="erreur"></span></li>
Kindly, for the sake of keeping your code base professional edit the typo for the class name. Also, as the project requirement the `show an error message to the user near the submit button informing them of the error`. Kindly, show the error after the `textarea` and before the `Get In Touch` button and give padding top.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/34578631/175517600-a33efdfa-05c6-45fd-9576-23519826de98.png">

2022-06-24 11:56 UTC, r-ahmed2022 commented on index.html
> +                 <li><span class="erreur"></span></li>
Done as advised

2022-06-24 13:08 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @a-laarabi 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 13:08 UTC, tresorsawasawa commented on menu.js
> +    error.innerHTML = 'email should be in lowercase';
- [ **OPTIONAL** ] What do you think about capitalizing the error message:  **Email shou... ** instead of **'email sho...** for good Egnlish syntax.

2022-10-06 04:41 UTC, merged